object Version {
    const val coreKtx = "1.7.0"
    const val appcompat = "1.4.0"
    const val androidKtx = "1.4.0"
    const val gradle = "7.0.4"
    const val kotlin = "1.5.21"
    const val hilt = "2.38.1"
    const val hiltCompose = "1.0.0"
    const val junit = "4.13.2"
    const val mockito = "4.2.0"
    const val androidJunit = "1.1.3"
    const val espresso = "3.4.0"
    const val mockitoKotlin = "2.2.0"
    const val mockitoInline = "2.21.0"
    const val jetpackCompose = "1.0.1"
    const val activityCompose = "1.4.0"
    const val lifecycle = "2.4.0"
    const val coroutine = "1.6.0"
}